# Generated by Django 5.2.1 on 2025-05-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=128)),
                ('is_active', models.BooleanField(default=1, max_length=1)),
            ],
        ),
    ]
