# Generated by Django 5.2.1 on 2025-05-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_usertasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTasks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_age',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
