# Generated by Django 5.2.1 on 2025-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_videopostura'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopostura',
            name='video',
            field=models.FileField(default='', upload_to='videos/'),
        ),
    ]
