# Generated by Django 5.2.1 on 2025-05-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_videopostura_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosturaCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deitado', models.IntegerField(default=0)),
                ('sentado', models.IntegerField(default=0)),
                ('em_pe', models.IntegerField(default=0)),
                ('movimento', models.IntegerField(default=0)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.videopostura')),
            ],
        ),
    ]
