# Generated by Django 5.2.1 on 2025-05-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_delete_usertasks_remove_user_user_age_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_nickname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
