# Generated by Django 5.2.1 on 2025-05-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_rename_user_nickname_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=1, max_length=1),
        ),
    ]
