# Generated by Django 5.2.1 on 2025-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_posturacount'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopostura',
            name='deitado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videopostura',
            name='em_pe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videopostura',
            name='movimento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videopostura',
            name='sentado',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PosturaCount',
        ),
    ]
