# Generated by Django 5.2.1 on 2025-05-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_videopostura_deitado_videopostura_em_pe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopostura',
            name='movimento',
        ),
    ]
