# Generated by Django 5.2.1 on 2025-05-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_remove_videopostura_movimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopostura',
            name='em_pe',
        ),
        migrations.AddField(
            model_name='videopostura',
            name='levantado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='videopostura',
            name='deitado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='videopostura',
            name='sentado',
            field=models.FloatField(default=0.0),
        ),
    ]
